sections = [
    "1. TITLE\nMEDIROUTE – Constraint-Aware Pharmacy Logistics Control Center",

    "2. ABSTRACT\nPharmacy delivery batching lowers courier distance and costs but risks missed deadlines, drug contamination, depot delays, overloaded cargo boxes, and rider fatigue. This 35% progress review report introduces MEDIROUTE, a constraint-aware control center optimizing delivery batching while enforcing hard operational safety boundaries. The system evaluates five mandatory constraints: delivery deadlines (with safety buffer), product compatibility, pickup readiness, rider capacity, and rider workload limits. At the 35% milestone, the database schema, 5-hard-constraint engine, priority greedy solver, baseline simulator, SQLite audit logger, Streamlit UI, and a 14-test-case verification suite are implemented and verified. Expected outcomes include reduced delivery distance and guaranteed constraint compliance.",

    "3. INTRODUCTION\nPharmacy last-mile delivery is time-critical; delays directly impact patient health. Pharmacies batch prescription orders to minimize delivery mileage and operating costs. Unlike e-commerce, last-mile delivery involves promised delivery windows, product exclusions, packaging limits, and preparation delays. Intelligent logistics systems must balance route efficiency with strict compliance to operational safety boundaries.",

    "4. PROBLEM STATEMENT\nDistance-only delivery batching focuses purely on proximity, ignoring operational safety rules. This causes six failure modes:\n- Delivery Deadlines: Intermediate stops delay deliveries, breaching promised time windows.\n- Product Compatibility: Grouping ColdChain drugs with Hazmat or Cytotoxic compounds creates contamination risks.\n- Pickup Readiness: Dispatching couriers before compounding completes causes idle depot waiting.\n- Rider Capacity: Exceeding motorcycle cargo box limits risks package damage or loss.\n- Rider Workload: Excessively long routes exceed driver fatigue limits (capped at 120 minutes continuous driving).\n- Unnecessary Distance: Uncoordinated individual dispatches create redundant travel mileage.",

    "5. OBJECTIVES\nThe main objectives of MEDIROUTE are:\n- Create feasible delivery batches by grouping compatible prescription orders.\n- Respect all five hard operational constraints (deadlines, product groups, pickup readiness, rider capacity, rider workload).\n- Assign orders to riders safely without exceeding physical or workload limits.\n- Reduce overall delivery distance compared to an unconstrained baseline.\n- Maintain an auditable, immutable record of batching decisions and rejection rationale.\n- Evaluate system robustness using realistic failure-case test scenarios.",

    "6. EXISTING SYSTEM\nConventional pharmacy delivery relies on individual dispatching or manual distance-only batching. Individual dispatching incurs separate round trips per order, causing high mileage, fuel waste, and low fleet utilization. Manual distance-based batching clusters orders by proximity alone, failing to verify stop delays, product exclusions, compounding readiness, or courier fatigue caps, causing frequent deadline breaches.",

    "7. PROPOSED SYSTEM\nMEDIROUTE is a constraint-aware decision-support control center. It prioritizes orders by urgency, evaluates candidate batch insertions against five hard constraints, and optimizes stop sequences. If any constraint is violated, the system rejects the insertion, logs a diagnostic reason, and evaluates alternative assignments. Key modules include order management, constraint validation, priority greedy batching, rider assignment, route planning, an immutable SQLite audit trail, baseline benchmarking, and failure testing.",

    "8. METHODOLOGY\nWorkflow: Orders Ingestion -> Priority Sorting -> Constraint Verification -> Feasible Batch Creation -> Rider Assignment -> TSP Route Sequencing -> Validation -> Audit Logging.\nHard constraints (rider capacity, product compatibility, pickup readiness delay, delivery deadlines with a 10-minute safety buffer, and rider workload limits) are strictly checked BEFORE a batch is considered valid. Only feasible insertions yielding net distance savings are accepted.",

    "9. SYSTEM MODULES\n- Overview: Executive dashboard displaying orders, active batches, and system status.\n- Orders: Ingests and manages prescription orders, priorities, product types, and deadlines.\n- Dispatch Planning: Formulates constraint-compliant plans using priority greedy solving.\n- Routes: Generates optimal stop sequences and timelines using exact TSP permutations.\n- Performance/Baseline Comparison: Benchmarks optimized plans against an unconstrained baseline.\n- Constraint Validation: Isolates and executes the 5 hard constraint checkers.\n- Audit Trail: Immutable log viewer for searching transaction histories and rejection reasons.\n- Stakeholder Feedback: Captures dispatcher and safety officer survey metrics.",

    "10. TECHNOLOGY USED\n- Python: Core language for logic, constraints, and solver.\n- Streamlit: Web framework for interactive control center UI.\n- SQLite: Database for persistent storage and audit logs.\n- Pandas: Data manipulation and tabular analysis.\n- Plotly: Interactive charting and visualization.\n- Pytest: Automated testing framework for unit and failure tests.",

    "11. CURRENT IMPLEMENTATION STATUS – 35%\nWork completed at the 35% milestone:\n- Functional Streamlit Web Application featuring an 8-module control center interface.\n- Database & Order Handling using SQLite (pharmacy.db) and synthetic data (500 orders, 20 riders, 30 products).\n- Baseline & Constraint-Aware Batching Engines for comparative evaluation.\n- 5-Hard-Constraint Engine validating capacity, workload, product compatibility, pickup readiness, and delivery deadlines.\n- Route Sequencing & Timeline Visualization using exact TSP permutations (n <= 6).\n- Immutable Audit Logging tracking plan initializations, state changes, and rejection reasons.\n- Failure-Case Simulator evaluating mandatory edge-case scenarios.\n- Enterprise Control Center UI Redesign for clear visual dispatch management.\nSystem correctness is verified by an automated Pytest suite containing exactly 14 test cases across constraints, batching, baseline, and failure scenarios (all 14 pass cleanly).",

    "12. FAILURE CASE VALIDATION\nThe system is validated against five mandatory failure scenarios:\n1. Tight Delivery Deadline: Rejects batching when added stops breach delivery deadlines.\n2. Incompatible Products: Rejects grouping ColdChain drugs with Hazmat or Cytotoxic compounds.\n3. Pickup Not Ready: Rejects batching orders requiring excessive pickup waiting (>90 mins).\n4. Rider Capacity Exceeded: Rejects batching when order count exceeds cargo box limits.\n5. Rider Workload Exceeded: Rejects routes exceeding the 120-minute continuous driving limit.\nThese test cases verify that MEDIROUTE never improves efficiency by violating operational safety constraints.",

    "13. EXPECTED RESULTS\nAs a 35% progress report, numerical results are not fabricated. Expected outcomes are:\n- Measurable reduction in total courier travel distance compared to individual dispatching.\n- 100% creation of valid, constraint-compliant delivery batches with zero hard violations.\n- Safe rider assignments adhering strictly to box capacity and workload fatigue limits.\n- Transparent, auditable log history capturing all operational decisions.\n- Demonstrated safety and operational improvement over the unconstrained baseline.",

    "14. FUTURE WORK\nPlanned development and future enhancements include:\n- Testing on larger real-world pharmacy dispatch datasets.\n- Route optimization and parallelized solving for larger order pools.\n- Broader stakeholder validation trials with dispatchers and safety officers.\n- System containerization, field deployment, and pilot testing.\n- Improved scalability and real-time dynamic re-batching capabilities.\n- Incorporating operational constraints such as live traffic updates and GPS tracking.",

    "15. CONCLUSION\nThe current 35% implementation establishes the core architectural and algorithmic foundation of MEDIROUTE. The 5-hard-constraint engine, greedy solver, baseline benchmark, SQLite audit system, Streamlit interface, and 14-test-case suite are fully operational. Remaining work will focus on large-scale experimentation, stakeholder validation, performance optimization, and final deployment.",

    "16. REFERENCES\n[1] P. Toth & D. Vigo, Eds., Vehicle Routing Problem, SIAM, 2014.\n[2] C. Archetti et al., \"VRP with time windows for pharmaceutical distribution,\" Comput. Oper. Res., 2015.\n[3] M. Savelsbergh & M. Sol, \"General pickup and delivery problem,\" Transp. Sci., 1995.\n[4] T. Vidal et al., \"Heuristics for multi-attribute VRP,\" Eur. J. Oper. Res., 2013.\n[5] G. Ghiani et al., Operations Research in Logistics & Supply Chain Management, Wiley, 2004.\n[6] M. Solomon, \"Algorithms for VRPTW,\" Oper. Res., 1987.\n[7] G. Laporte, \"The vehicle routing problem: An overview,\" Eur. J. Oper. Res., 1992."
]

# Let's perform precise text tightening to hit < 7800 chars
t = "\n\n".join(sections)

# Let's do replacements to tighten
t = t.replace("Pharmacy delivery batching lowers courier distance and costs but risks missed deadlines, drug contamination, depot delays, overloaded cargo boxes, and rider fatigue.", "Pharmacy delivery batching reduces courier mileage but risks missed deadlines, drug contamination, depot delays, overloaded boxes, and rider fatigue.")
t = t.replace("Unlike e-commerce, pharmacy delivery involves promised delivery windows, handling exclusions, packaging limits, and preparation delays.", "Unlike e-commerce, pharmacy delivery involves promised windows, product exclusions, packaging limits, and preparation delays.")
t = t.replace("Manual or simple distance-only delivery batching focuses purely on geographic proximity, ignoring operational safety rules.", "Distance-only delivery batching focuses purely on geographic proximity, ignoring operational safety rules.")
t = t.replace("Conventional pharmacy delivery relies on individual dispatching or manual distance-only batching.", "Conventional pharmacy delivery relies on individual dispatching or manual distance-only batching.")
t = t.replace("System correctness is verified by an automated Pytest suite containing exactly 14 test cases across constraints, batching, baseline, and failure scenarios (all 14 pass cleanly).", "System correctness is verified by an automated Pytest suite containing 14 test cases across constraints, batching, baseline, and failure scenarios (all 14 pass).")

# Let's tighten each section slightly
t = t.replace("MEDIROUTE is a constraint-aware decision-support control center. It prioritizes orders by urgency, evaluates candidate batch insertions against five hard constraints, and optimizes stop sequences. If any constraint is violated, the system rejects the insertion, logs a diagnostic reason, and evaluates alternative assignments.", "MEDIROUTE is a constraint-aware control center prioritizing orders by urgency, evaluating candidate insertions against five hard constraints, and optimizing stop sequences. If any constraint is violated, the system rejects the insertion, logs a diagnostic reason, and evaluates alternative assignments.")

print("New count:", len(t))

with open("final_report_strict.txt", "w", encoding="utf-8") as f:
    f.write(t)
